### ISSUE TITLE
Properly attribute Windows Community Toolkit License

### ISSUE THREAD

**Issue by michael-hawker** [ModernWpf-Community/ModernWpfCommunityToolkit#5]
Hi!

Really great to see someone back-porting some Windows Community Toolkit code to WPF!

However, I noticed some of the license notices have been stripped from the code copied over (or maybe it's not clear which ones are unique to this project to call out your own license). You still need to preserve the headers for files from the WCT and preserve the copyright within the license:

```
Copyright (c) .NET Foundation and Contributors
All rights reserved.
```

Either calling it out in your license file at the top with your name or using a [third-party notice file](https://github.com/windows-toolkit/WindowsCommunityToolkit/blob/master/ThirdPartyNotices.txt) with a copy of [our license](https://github.com/windows-toolkit/WindowsCommunityToolkit/blob/master/license.md).

Thanks!

**Comment by ShankarBUS** [comment]
OMG @michael-hawker!!!

Thank you for your kindly reminder.

I'll take care of this.

Thanks again for being polite!

**Comment by ShankarBUS** [comment]
'

**Comment by ShankarBUS** [comment]
Correct me if I'm wrong

The code which are copied from WCT have this following header statement

```
// Licensed to the .NET Foundation under one or more agreements.

// The .NET Foundation licenses this file to you under the MIT license.

// See the LICENSE file in the project root for more information.
```

Only code files that I added don't have that as the header

I'm not aware of any of these licensing or copyright procedures or rules.

Is appending this to the license enough?

```
Copyright (c) .NET Foundation and Contributors
All rights reserved.
```

I'll also add the credits to the WCT in the README and will add the ThirdPartyNotices with the WCT License

Sorry for being silly. Could you guide me on this topic?

I'm sorry if i breached any rules or regulations.

**Comment by michael-hawker** [comment]
No worries @ShankarBUS, knew it was just an oversight. 🙂

I think the main piece for compliance is updating the license like this:

```
MIT License

Copyright (c) .NET Foundation and Contributors
All rights reserved.

Copyright (c) 2020 Shankar

Permission is hereby ...
```

For clarity, it'd help for any files you have added yourself to have your own header to each of those files too:

```
// Copyright (c) Shankar
// This file is licensed to you under the MIT license.
// See the LICENSE file in the project root for more information.
```

Anything beyond that, like call out/links in the readme is just extra appreciation. 🎉

**Comment by ShankarBUS** [comment]
Ahhh Thanks XAML Llama!

I will make those changes ASAP.
