### ISSUE TITLE
Can i get a wiki for the use of the markdowntextblock?

### ISSUE THREAD

**Issue by dayAndnight2018** [ModernWpf-Community/ModernWpfCommunityToolkit#7]
for example, can i get a help for the use of add a picture?

**Comment by ShankarBUS** [comment]
The **MarkdownTextBlock** control present in this toolkit is to similar to the one in the **Windows Community Toolkit.**
They have an amazing documentation at MS Docs (see https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/markdowntextblock)

For some this toolkit specific things, see #6 and https://github.com/ShankarBUS/ModernFlyouts/blob/b852f6cc7a4e6a207012251cec5ff90e82da5d75/ModernFlyouts/App.xaml#L10-L47 to learn how to set it up before using.

You can see my app's code to see how I made it to handle hyperlinks and image fetching.
[AboutPage.xaml (xaml)](https://github.com/ShankarBUS/ModernFlyouts/blob/b852f6cc7a4e6a207012251cec5ff90e82da5d75/ModernFlyouts/Navigation/AboutPage.xaml)
[AboutPage.xaml.cs (code behind)](https://github.com/ShankarBUS/ModernFlyouts/blob/b852f6cc7a4e6a207012251cec5ff90e82da5d75/ModernFlyouts/Navigation/AboutPage.xaml.cs)

The image you want to show in the markdown textblock must be included as a **resource** or **content** (with copy to output directory enabled). (just like how you do normally to show images in WPF. Nothing new)

You can also modify it to your own needs like this:

```cs
        private void MarkdownTextBlock_ImageResolving(object sender, ImageResolvingEventArgs e)
        {
            if (Uri.TryCreate(e.Url, UriKind.Absolute, out Uri result))
            {
                e.Image = new BitmapImage(result);
                e.Handled = true;
                return;
            }
            else
            {
                try /* for loading local images*/
                {
                    e.Image = new BitmapImage(new Uri("pack://application:,,,/YourAssemblyNameGoesHere;component/" + e.Url));
                    e.Handled = true;
                    return;
                }
                catch { return; }
            }
        }
```

Please be patient. I've plans to improve the usability of this toolkit and reduce work on your side. I will let you know once this toolkit is usable. It's still in alpha (meaning not ready for production use). So, please bear with us 😅.

**Comment by ShankarBUS** [comment]
@dayAndnight2018,

v0.1 has been released recently. Please install/update to the latest version of the toolkit.
I have updated the sample app. You could use it as a reference.
Please check this out - https://github.com/ModernWpf-Community/ModernWpfCommunityToolkit/tree/8bbe2231087575df182a7740839b92e917fa711b/ModernWpf.Toolkit.SampleApp
